/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 30 07:47:12 GMT 2016
 */

package account;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import account.Account;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Account_ESTest extends Account_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account.main(stringArray0);
      Account.main(stringArray0);
      Account.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account.main(stringArray0);
      Account account0 = new Account();
      Account.main(stringArray0);
      account0.go(stringArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account.main(stringArray0);
      Account account0 = new Account();
      Account.main(stringArray0);
      account0.checkResult(0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account.main(stringArray0);
      Account.main(stringArray0);
      // Undeclared exception!
      try { 
        Account.Service(246, 246);
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 246
         //
         verifyException("account.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account.main(stringArray0);
      Account account0 = new Account();
      account0.go(stringArray0);
      Account.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[4];
      Account.main(stringArray0);
      account0.go(stringArray0);
      account0.go(stringArray0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[4];
      Account.main(stringArray0);
      account0.go(stringArray0);
      // Undeclared exception!
      try { 
        account0.checkResult(98);
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account.main(stringArray0);
      Account account0 = new Account();
      account0.go(stringArray0);
      // Undeclared exception!
      try { 
        Account.Service(246, 246);
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 246
         //
         verifyException("account.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account.main(stringArray0);
      Account account0 = new Account();
      account0.checkResult(0);
      Account.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account.main(stringArray0);
      Account account0 = new Account();
      account0.checkResult(0);
      account0.go(stringArray0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account.main(stringArray0);
      Account account0 = new Account();
      account0.checkResult(0);
      account0.checkResult(0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account.main(stringArray0);
      Account account0 = new Account();
      account0.checkResult(0);
      // Undeclared exception!
      try { 
        Account.Service(246, 246);
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 246
         //
         verifyException("account.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[3];
      Account.main(stringArray0);
      Account.Service(0, 0);
      Account.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[4];
      Account.main(stringArray0);
      Account.Service(0, 98);
      // Undeclared exception!
      try { 
        account0.go(stringArray0);
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[4];
      Account.main(stringArray0);
      Account.Service(0, 98);
      account0.checkResult(98);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String[] stringArray0 = new String[3];
      Account.main(stringArray0);
      Account.Service(0, 0);
      Account.Service(0, 0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.checkResult(0);
      Account.main(stringArray0);
      account0.go(stringArray0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String[] stringArray0 = new String[4];
      Account account0 = new Account();
      account0.checkResult(0);
      Account.main(stringArray0);
      // Undeclared exception!
      try { 
        account0.checkResult(968);
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account account0 = new Account();
      account0.checkResult(0);
      account0.go(stringArray0);
      Account.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Account account0 = new Account();
      account0.checkResult(0);
      account0.go((String[]) null);
      account0.checkResult(0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account account0 = new Account();
      account0.checkResult(0);
      account0.checkResult(0);
      Account.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account account0 = new Account();
      account0.checkResult(0);
      account0.checkResult(0);
      account0.go(stringArray0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Account account0 = new Account();
      account0.checkResult(0);
      account0.checkResult(0);
      account0.checkResult(0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      account0.checkResult(0);
      Account.Service(0, 0);
      account0.go(stringArray0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Account account0 = new Account();
      account0.go((String[]) null);
      account0.checkResult(0);
      Account.Service(1, 1);
      account0.checkResult(1);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Account account0 = new Account();
      account0.go((String[]) null);
      account0.checkResult(0);
      Account.Service(1, 1);
      // Undeclared exception!
      try { 
        Account.Service(160, 160);
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 160
         //
         verifyException("account.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      Account.main(stringArray0);
      Account.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      Account.main(stringArray0);
      account0.go(stringArray0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      Account.main(stringArray0);
      account0.checkResult(0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      account0.go(stringArray0);
      Account.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      account0.go(stringArray0);
      account0.go(stringArray0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      account0.go(stringArray0);
      account0.checkResult(0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      account0.go(stringArray0);
      Account.Service(0, 0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      account0.checkResult(0);
      Account.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Account account0 = new Account();
      account0.go((String[]) null);
      String[] stringArray0 = new String[4];
      Account.Service(0, 98);
      account0.checkResult(98);
      // Undeclared exception!
      try { 
        account0.go(stringArray0);
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      Account.Service(0, 0);
      Account.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      Account.Service(0, 0);
      account0.go(stringArray0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      // Undeclared exception!
      try { 
        Account.Service(1, 1);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("account.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      Account.Service(0, 0);
      Account.Service(0, 0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account account0 = new Account();
      account0.checkResult(0);
      Account.main(stringArray0);
      // Undeclared exception!
      try { 
        Account.Service(246, 246);
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 246
         //
         verifyException("account.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Account account0 = new Account();
      account0.checkResult(0);
      account0.go(stringArray0);
      // Undeclared exception!
      try { 
        Account.Service(246, 246);
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 246
         //
         verifyException("account.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Account account0 = new Account();
      account0.checkResult(0);
      account0.checkResult(0);
      // Undeclared exception!
      try { 
        Account.Service(246, 246);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("account.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[3];
      account0.go(stringArray0);
      Account.Service(0, 0);
      Account.main(stringArray0);
      Account.Service(0, 0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Account account0 = new Account();
      account0.go((String[]) null);
      Account.Service(1, 1);
      account0.checkResult(1);
      // Undeclared exception!
      try { 
        Account.Service(160, 160);
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 160
         //
         verifyException("account.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Account account0 = new Account();
      String[] stringArray0 = new String[9];
      account0.Bank_random = null;
      // Undeclared exception!
      try { 
        Account.main(stringArray0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Account account0 = new Account();
      account0.NUM_ACCOUNTS = (-1415);
      // Undeclared exception!
      try { 
        account0.go((String[]) null);
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("account.Account", e);
      }
  }
}
